version: 0.2

env:
  variables:
    ORIGIN_BUCKET: "my_bucket"
    DISTRIBUTION_ID: "my_distribution_id"

phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - aws s3 sync --delete ./src s3://$ORIGIN_BUCKET
      - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --path "/*"